composer/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import logout

app_name = 'composer'

urlpatterns = [

    # /composer/
    url(r'^$', views.HomeView.as_view(), name='home'),

    # /composer/registration
    url(r'^registration$', views.RegistrationView.as_view(), name='registration'),

    # /composer/login
    url(r'^login$', views.LoginView.as_view(), name='login'),

    # /composer/profile
    url(r'^profile$', views.ProfileView.as_view(), name='profile'),

    # /composer/logout
    url(r'^logout$', logout, {'next_page': '/composer/'},name='logout'),

    # /composer/projects
    url(r'^projects$', views.ProjectsView.as_view() ,name='projects'),

    # /composer/projects/new
    url(r'^projects/new$', views.NewProjectView.as_view() ,name='new_project'),

    # /composer/project/<pk>
    url(r'^project/(?P<pk>[0-9]+)/$', views.CurrentProjectView.as_view() ,name='project'),

    # /composer/project/<pk>/delete
    url(r'^project/(?P<pk>[0-9]+)/delete/', views.SongDelete.as_view() ,name='delete-song'),

]

music_processing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^composer/', include('composer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

composer/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import validate_file_extension
from django.core.urlresolvers import reverse
import os
from django.conf import settings

class Project(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    no_of_songs = models.IntegerField(default=0)

    def get_absoulte_url(self):
        return reverse('composer:project',kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + ' ' + str(self.no_of_songs)

class Song(models.Model):
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    file = models.FileField(upload_to='songs/',validators=[validate_file_extension])
    name = models.CharField(max_length=250,default='')

    def __str__(self):
        return self.name

    def save(self, *args,**kwargs):

        basename, extension = os.path.splitext(os.path.basename(self.file.url))
        self.name = basename
        super(Song,self).save(*args,**kwargs)

    def delete(self):

        pk = self.project.pk
        no_of_songs = self.project.no_of_songs - 1

        Project.objects.filter(pk=pk).update(no_of_songs=no_of_songs)

        os.remove("F:\Licenta\music_processing" + self.file.url)
        return super(Song,self).delete()

composer/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import  authenticate,login
from .models import Project,Song

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['email','username','password']

class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self,*args,**kwargs):

        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username,password=password)
        if username and password:
            user = User.objects.get(username=username)
            if not user:
                raise forms.ValidationError("This user does not exist!")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password!")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer active!")
        return super(LoginForm,self).clean(*args,**kwargs)

class ProjectForm(forms.ModelForm):

    class Meta:

        model = Project
        fields = ['name']

class SongForm(forms.ModelForm):

    class Meta:

        model = Song
        fields = ['file']

composer/views.py
from django.views import generic
from django.shortcuts import render,redirect
from .forms import *
from .models import Project,Song
from django.core.urlresolvers import reverse_lazy

class HomeView(generic.TemplateView):

    template_name = 'composer/home.html'

class RegistrationView(generic.TemplateView):

    form_class = UserForm
    template_name = 'composer/registration.html'

    def get(self,request):

        if request.user.is_authenticated :

            return redirect('composer:profile')

        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form })

    def post(self,request):

        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            return render(request, self.template_name, {'form': form})

        return render(request, self.template_name, {'form' : form })

class LoginView(generic.TemplateView):

    form_class = LoginForm
    template_name = 'composer/login.html'

    def get(self,request):

        if request.user.is_authenticated :

            return redirect('composer:home')

        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form })

    def post(self,request):

        form = self.form_class(request.POST)

        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username,password=password)

            login(request, user)
            return redirect('composer:profile')

        else:

            return render(request, self.template_name, {'form': form })

class ProfileView(generic.TemplateView):

    template_name = 'composer/profile.html'

    def get(self, request):

        if not request.user.is_authenticated :

            return redirect('composer:home')

        return render(request,self.template_name)

class ProjectsView(generic.ListView):

    template_name = 'composer/projects.html'
    context_object_name = 'all_projects'

    def get_queryset(self):

        return Project.objects.filter(user=self.request.user)

class NewProjectView(generic.TemplateView):

    template_name = 'composer/projects/new.html'
    form_class = ProjectForm

    def get(self, request):

        if not request.user.is_authenticated :

            return redirect('composer:home')

        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):

        form = self.form_class(request.POST)

        if form.is_valid():

            project = form.save(commit=False)

            project.user = self.request.user

            project.save()

            return redirect('composer:projects')

        else:

            return render(request, self.template_name, {'form': form})

class CurrentProjectView(generic.CreateView):

    template_name = 'composer/project.html'
    form_class = SongForm

    def get_context_data(self, **kwargs):

        pk = self.kwargs['pk']

        project = Project.objects.get(pk=pk)

        kwargs['all_songs'] = Song.objects.filter(project=project)

        return super(CurrentProjectView,self).get_context_data(**kwargs)

    def post(self, request,pk):

        form = self.form_class(request.POST,request.FILES)

        project = Project.objects.get(pk=pk)

        if form.is_valid():

            song = form.save(commit=False)

            song.project = project

            project.no_of_songs += 1

            project.save()

            song.save()

            return redirect('composer:project',pk=pk)

        else:

            return render(request, self.template_name, {'form': form})

class SongDelete(generic.DeleteView):

    model = Song

    def get_success_url(self):
        project = self.object.project
        return reverse_lazy('composer:project',kwargs={'pk' : project.id})

composer/templates/composer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Musical composer{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"  href="{% url 'composer:home' %}">
                Musical composer
            </a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">

            {% if user.is_authenticated %}

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'composer:profile' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                            Profile
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'composer:projects' %}">
                            <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp;
                            Projects
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'composer:logout' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;
                            Log out
                        </a>
                    </li>
                </ul>

            {% else %}

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'composer:registration' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Sign up
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'composer:login' %}">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;
                            Login
                        </a>
                    </li>
                </ul>

            {% endif %}

        </div>

    </div>
</nav>
    {% block body %}
    {% endblock %}
</body>
</html>

composer/templates/composer/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-5">{{ field.label_tag }}</label>
        <div class="col-sm-20">{{ field }}</div>
    </div>
{% endfor %}

composer/templates/composer/home.html
{% extends 'composer/base.html' %}

{% block body %}

      <h1>Welcome to my site!</h1>

{% endblock %}

composer/templates/composer/login.html
{% extends 'composer/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="col-sm-offset-4">Login to existing account</h3>
                        <br>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'composer/form-template.html' %}
                            <div class="col-sm-offset-4">{{ form.non_field_errors }}</div>
                            <div class="form-group">
                                <div class="col-sm-offset-5 col-sm-12">
                                    <button type="submit" class="btn btn-success">Log in</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

composer/templates/composer/profile.html
{% extends 'composer/base.html' %}

{% block body %}

      <h1>Welcome to your profile {{ request.user.username }}!</h1>

{% endblock %}

composer/templates/composer/project.html
{% extends 'composer/base.html' %}
{% load staticfiles %}

{% block body %}

    <div class="container">

        <div class="row">

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="col-sm-offset-5">Add new song</h3>
                        <br>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'composer/form-template.html' %}
                            <div class="col-sm-offset-4">{{ form.errors }}</div>
                            <div class="form-group">
                                <div class="col-sm-offset-5 col-sm-12">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <div class="col-md-4">
        <ul class="list-group">
            {% if all_songs %}
                {% for song in all_songs %}
                    <li class="list-group-item">
                        {{ song.name }} &nbsp;
                        <form action="{% url 'composer:delete-song' song.id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="song_id" value="{{ song.id }}"/>
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                        <audio controls autoplay src="C:\Users\Matei\Downloads\My_Heart_Will_Go_On_Official_Music_Video_With_Lyri.wav"></audio>
                    </li>
                {% endfor %}
            {% else %}
                <h1 style="opacity:0.5;">No available songs</h1>
            {% endif %}
        </ul>
    </div>

{% endblock %}

composer/templates/composer/projects.html
{% extends 'composer/base.html' %}

{% block body %}

    <div class="col-md-4">
        <a href="{% url 'composer:new_project' %}" class="btn btn-info" role="button">New project</a>
    </div>

    <div class="col-md-4">
        <ul class="list-group">
            {% if all_projects %}
                {% for project in all_projects %}
                    <a href="{% url 'composer:project' project.pk %}" style="text-decoration:none;">
                        <li class="list-group-item">
                            {{ project.name }}
                            <span class="badge badge-default badge-pill">{{ project.no_of_songs }}</span>
                        </li>
                    </a>
                {% endfor %}
            {% else %}
                <h1 style="opacity:0.5;">No available projects</h1>
            {% endif %}
        </ul>
    </div>

{% endblock %}

composer/templates/composer/projects/new.html
{% extends 'composer/base.html' %}
{% block title %}Registration{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="col-sm-offset-4">Create new project</h3>
                        <br>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'composer/form-template.html' %}
                            <div class="col-sm-offset-4">{{ form.errors }}</div>
                            <div class="form-group">
                                <div class="col-sm-offset-5 col-sm-12">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

composer/templates/composer/registration.html
{% extends 'composer/base.html' %}
{% block title %}Registration{% endblock %}

{% block body %}

    <div class="container">

        <div class="row">

            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="col-sm-offset-4">Create new account</h3>
                        <br>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'composer/form-template.html' %}
                            <div class="col-sm-offset-4">{{ form.errors }}</div>
                            <div class="form-group">
                                <div class="col-sm-offset-5 col-sm-12">
                                    <button type="submit" class="btn btn-success">Sign up</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}